#!/bin/bash

python reaching.py $1

rm -f IMP/*.pyc
rm -f generate.pyc

cp reaching_constant.txt execute.py

sed -i -e '/#DECLARE-Vars/r vars.txt' execute.py
sed -i -e '/#DECLARE-Labs/r labs.txt' execute.py
sed -i -e '/#DECLARE-BoolVectors/r boolvectors.txt' execute.py
sed -i -e '/#DECLARE-enex/r enex.txt' execute.py
sed -i -e '/#DECLARE-statements/r statements.txt' execute.py

rm -f vars.txt
rm -f labs.txt
rm -f boolvectors.txt
rm -f enex.txt
rm -f statements.txt
rm -f execute.py-e

python execute.py $2
rm -f execute.py
